### ISSUE TITLE
config.bat fails for openalea-incbator/caribu

### ISSUE THREAD

**Issue by christian34** [openalea/appveyor-ci#1]
config .bat seems to fail when run from openalinea-incubator (see eg https://ci.appveyor.com/project/pradal/caribu)

**Comment by pfernique** [comment]
Try again but with:
* ANACONDA_OWNER set to the value of ANACONDA_UPLOAD (deprecated)
* ANACONDA_LOGIN set to the value of ANACONDA_USERNAME (deprecated)

**Comment by pfernique** [comment]
Seems to be resolved now. Closing the issue.
